version: "3.8"
services:
  app:
    build: .
    container_name: the_drop_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=Tha Drop
    env_file:
      - .env
    networks:
      - the_drop_network

networks:
  the_drop_network:
    driver: bridge
